Repository lektor/lektor, pull requests merged in 2022-01, with the labels that each got.

#980 Admin: complete typing for API fetch requests
  .pre-commit-config.yaml
  lektor/admin/.eslintrc.js
  lektor/admin/static/js/components/ErrorDialog.tsx
  lektor/admin/static/js/components/RecordComponent.test.ts
  lektor/admin/static/js/components/RecordComponent.tsx
  lektor/admin/static/js/components/ServerStatus.tsx
  lektor/admin/static/js/components/ToggleGroup.test.tsx
  lektor/admin/static/js/components/ToggleGroup.tsx
  lektor/admin/static/js/dialogs/Publish.tsx
  lektor/admin/static/js/dialogs/Refresh.tsx
  lektor/admin/static/js/dialogs/find-files/FindFiles.tsx
  lektor/admin/static/js/dialogs/find-files/ResultRow.tsx
  lektor/admin/static/js/error-dialog.ts
  lektor/admin/static/js/events.ts
  lektor/admin/static/js/fetch.ts
  lektor/admin/static/js/header/BreadCrumbs.tsx
  lektor/admin/static/js/header/GlobalActions.tsx
  lektor/admin/static/js/main.tsx
  lektor/admin/static/js/sidebar/PageActions.tsx
  lektor/admin/static/js/sidebar/Sidebar.tsx
  lektor/admin/static/js/utils.test.ts
  lektor/admin/static/js/utils.ts
  lektor/admin/static/js/views/AddAttachmentPage.tsx
  lektor/admin/static/js/views/PreviewPage.tsx
  lektor/admin/static/js/views/add-child-page/AddChildPage.tsx
  lektor/admin/static/js/views/delete/DeletePage.tsx
  lektor/admin/static/js/views/edit/EditPage.tsx
Labels: admin-related

#983 Mark test that requires internet
  pyproject.toml
  pytest.ini
  tests/test_pluginsystem.py
  tox.ini
Labels: enhancement, testing

#976 Refactor admin URLs
  lektor/admin/modules/common.py
  lektor/admin/modules/dash.py
  lektor/admin/modules/serve.py
  lektor/admin/static/js/components/AdminLink.tsx
  lektor/admin/static/js/components/RecordComponent.test.ts
  lektor/admin/static/js/components/RecordComponent.tsx
  lektor/admin/static/js/components/types.ts
  lektor/admin/static/js/components/use-go-to-admin-page.ts
  lektor/admin/static/js/dialogs/find-files/FindFiles.tsx
  lektor/admin/static/js/dialogs/find-files/ResultRow.tsx
  lektor/admin/static/js/fetch.ts
  lektor/admin/static/js/header/BreadCrumbs.tsx
  lektor/admin/static/js/main.tsx
  lektor/admin/static/js/sidebar/ChildActions.tsx
  lektor/admin/static/js/utils.ts
  lektor/admin/static/js/views/App.tsx
  lektor/admin/static/js/views/PreviewPage.tsx
  lektor/admin/webui.py
  tests/test_webui.py
Labels: alternatives, admin-related

#964 Logic error in make_editor_session
  CHANGES.md
  lektor/editor.py
  tests/test_editor.py
Labels: bug, alternatives, testing

#967 Clean up `lektor.admin.modules.api`
  lektor/admin/modules/api.py
  lektor/db.py
  lektor/editor.py
  tests/test_api.py
  tests/test_tree.py
Labels: bug, alternatives

#994 Fix installation of ImageMagick on Windows test runner
  .github/workflows/ci.yml
Labels: bug, ci
